POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title": "EROOTTINEN NOVELLIKOKOELMA: MITÄ HALUAISIT LUKEA?",
  "author": "Sita Salminen",
  "url": "https://sitasalminen.fi/lifestyle/eroottinen-novellikokoelma-mita-haluaisit-lukea/",
  "likes": 48,
  "id": "112233"
}